### PR TITLE
Add Elastic Agent to mobile config template

### PR DESCRIPTION
**Pull request by aleksmaus**

### CODE REVIEW

**Comment by aleksmaus** [comment]
Tested with help of @brunerd, who pushed the newly generated profile to my dev box
Screen Shot 2022-10-19 at 5 09 34 PM
Screen Shot 2022-10-19 at 5 09 25 PM

Confirmed the osquery returns results from protected directories as expected
Screen Shot 2022-10-19 at 5 08 45 PM

**Review by ricardoungureanu — APPROVED** [review]
LGTM

**Comment by aleksmaus** [comment]
It doesn't look that I have permissions to merge this PR. Could anybody merge it or give me permissions to do so?

**Comment by ricardoungureanu** [comment]
@aleksmaus we need one more review to be able to merge it

**Comment by aleksmaus** [comment]
@ferullo @gabriellandau guys, could you 👍 ?

**Review by gabriellandau — APPROVED** [review]

**Comment by aleksmaus** [comment]
agreed to wait on @Trinity2019 approval and please merge whoever has the permissions, cause I don't have them.

**Pull request merged**
