### PR TITLE
Elastic security deployment manifest

### PR DESCRIPTION
**Pull request by lrishi**
This PR adds the manifest for deploying elastic-security (endpoint-security, elastic-agent and k8s metadata fetcher) in a Kubernetes cluster.
This manifest has been tested on EKS and GKE.
This is based on elastic-agent's [managed deployment manifest](https://github.com/elastic/elastic-agent/blob/689aee33c923be6183267c0e45596aa8d758e6eb/deploy/kubernetes/elastic-agent-managed-kubernetes.yaml).

### CODE REVIEW

**Comment by lrishi** [comment]
Cc: @benironside

**Review by daniel-almeida — APPROVED** [review]
:shipit:

**Review by nick-alayil — CHANGES_REQUESTED** [review]
I believe the daemonset should be named as elastic-agent, which aligns with elastic's [ideology](https://www.elastic.co/elastic-agent) of single agent and all integrations underneath it.

**Review by nick-alayil — APPROVED** [review]
LGTM. Ship it.

**Comment by ferullo** [comment]
LGTM

**Review by ferullo — APPROVED** [review]

**Review by softengchick — APPROVED** [review]

**Pull request merged**
